[package]
name = "poker-solver"
version = "0.1.0"
authors = ["hucancode <hucancode@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
tokio = { version = "1.28.0", features = ["rt", "macros" ] }
wasm-bindgen = { version = "0.2.63" }

[profile.release]
lto = true
debug = true

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "poker"
path = "src/main.rs"
required-features = ["multi-thread"]

[features]
default = []
multi-thread = ["tokio/rt-multi-thread"]
